title: Compromised Haven
description: Краткий справочник по дисциплинам VtM 5th edition
show_downloads: false
markdown: GFM
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
remote_theme: pages-themes/cayman@v0.2.0
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
